language: generic
sudo: required
services: 
    - docker

before_install:
    - docker build -t alinafembendera/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true alinafembendera/docker-react npm run test -- --coverage  

deploy:
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-1-344161852692"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
